# Data extraction and summarization of simulated datasets:
# After the looping-procedure: extract the averaged data generated by the output
# from the acc.curve.sim-function.
# Requires a stored object with all data generated by the acc.curve.sim-function

acc.curve.xtr.avg <- function(genotypes, samples, object, statistic) {

	pop.vec <- sapply(1:length(genotypes), function(i) max(genotypes[[i]]) )

	# Extract the population size estimates
	avg.est <- vector("list",length=length(genotypes)) 
	# 4 for mean, 3 for median
	if (statistic=="mean")
		stat <- 4
	else if (statistic=="median")
		stat <- 3
	else stop ("Not a valid statistic parameter!")

	for (j in 1:length(genotypes)) {
		avg.dat <- sapply(1:length(samples), function(i) as.vector(object[[1]][[j]][[i]][stat,]) )
		avg.est[[j]] <- t(avg.dat)
		}

	avg <- function(genotypes, model) {
	dat <- sapply(1:length(genotypes), function (i) avg.est[[i]][,model])
	colnames(dat) <- pop.vec
	rownames(dat) <- samples
	dat
	}

	kohn.avg <- avg(genotypes,1) 
	eggert.avg <- avg(genotypes,2)
	chessel.avg <- avg(genotypes,3)

	# Extract quantile intervals
	qi.est <- vector("list",length=length(genotypes))

	for (j in 1:length(genotypes)) {
		qi.dat <- sapply(1:length(samples), function(i) as.vector(object[[1]][[j]][[i]][c(7,8),]) )
		qi.est[[j]] <- t(qi.dat)
		}

	qis <- function(genotypes,model) {
		if (model==1) ind <- c(1,2)
		if (model==2) ind <- c(3,4)
		if (model==3) ind <- c(5,6)

	dat <- lapply(1:length(genotypes), function (i) qi.est[[i]][,ind])
		for (i in 1:length(genotypes)) colnames(dat[[i]]) <- c("2.5%","97.5%")
		for (i in 1:length(genotypes)) rownames(dat[[i]]) <- samples
	dat
	}

	kohn.qi <- qis(genotypes,1)
	eggert.qi <- qis(genotypes,2)
	chessel.qi <- qis(genotypes,3)

	# Estimate bias, each function at the time

	TruePop <- matrix(rep(pop.vec,length(samples)),nrow=length(samples),ncol=length(genotypes),byrow=T )

	# Bias function
	# model: 1 = Kohn, 2 = Eggert, 3 = Chessel
	bias.est <- function(input, TruePop) {
	bias.mat <- (input-TruePop) / TruePop
	dat <- 100*bias.mat
	colnames(dat) <- pop.vec
	rownames(dat) <- samples
	dat
	}

	kohn.bias <- bias.est(kohn.avg,TruePop)
	eggert.bias <- bias.est(eggert.avg,TruePop)
	chessel.bias <- bias.est(chessel.avg,TruePop)

	# Create output
	list(
		kohn = list(samples = samples, avg.est = kohn.avg, qi = kohn.qi, bias = kohn.bias, prop.found = object[[3]]),
		eggert = list(samples = samples, avg.est = eggert.avg, qi = eggert.qi, bias = eggert.bias, prop.found = object[[3]]),
		chessel = list(samples = samples, avg.est = chessel.avg, qi = chessel.qi, bias = chessel.bias, prop.found = object[[3]])
	)
}
